name: Build Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The CoreELEC version to build'
        required: false
        default: '21.2-Omega'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make gcc git texinfo gzip squashfs-tools
          sudo apt-get install autoconf automake libtool
      

      - name: Run Build
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          cd ~/e900v22c-CoreELEC
          sh build.sh

